// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dccphvldoxrqxlwabysi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjY3Bodmxkb3hycXhsd2FieXNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNTg2MjYsImV4cCI6MjA1NzczNDYyNn0.z63ywN6fs9NI2KHA-i5w7C0PO0WWeQO56iSDlfxWU4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);